# Using a Neural network to fit the data

In [32]:
from collections import OrderedDict

In [7]:
import torch.nn as nn
import torch
import torch.optim as optim

In [3]:
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c).unsqueeze(1) # <1>
t_u = torch.tensor(t_u).unsqueeze(1) # <1>

t_u.shape

torch.Size([11, 1])

In [4]:
n_samples = t_u.shape[0]
n_val = int(0.2 * n_samples)

shuffled_indices = torch.randperm(n_samples)

train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_indices, val_indices

(tensor([2, 6, 8, 5, 7, 9, 4, 0, 1]), tensor([10,  3]))

In [5]:
t_u_train = t_u[train_indices]
t_c_train = t_c[train_indices]

t_u_val = t_u[val_indices]
t_c_val = t_c[val_indices]

t_un_train = 0.1 * t_u_train
t_un_val = 0.1 * t_u_val

In [6]:
linear_model = nn.Linear(1, 1)
linear_model(t_un_val)

tensor([[4.6696],
        [5.6658]], grad_fn=<AddmmBackward0>)

In [8]:
linear_model = nn.Linear(1, 1) # <1>
optimizer = optim.SGD(
    linear_model.parameters(), # <2>
    lr=1e-2)

In [9]:
linear_model.parameters()

<generator object Module.parameters at 0x0000023ECBDAF5A0>

In [10]:
list(linear_model.parameters())

[Parameter containing:
 tensor([[0.0904]], requires_grad=True),
 Parameter containing:
 tensor([0.6745], requires_grad=True)]

In [11]:
def training_loop(n_epochs, optimizer, model, loss_fn, t_u_train, t_u_val,
                  t_c_train, t_c_val):
    for epoch in range(1, n_epochs + 1):
        t_p_train = model(t_u_train) # <1>
        loss_train = loss_fn(t_p_train, t_c_train)

        t_p_val = model(t_u_val) # <1>
        loss_val = loss_fn(t_p_val, t_c_val)
        
        optimizer.zero_grad()
        loss_train.backward() # <2>
        optimizer.step()

        if epoch == 1 or epoch % 1000 == 0:
            print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"
                  f" Validation loss {loss_val.item():.4f}")

In [13]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

linear_model = nn.Linear(1, 1) # <1>
optimizer = optim.SGD(linear_model.parameters(), lr=1e-2)

training_loop(
    n_epochs = 30000, 
    optimizer = optimizer,
    model = linear_model,
    loss_fn = loss_fn,
    t_u_train = t_un_train,
    t_u_val = t_un_val, 
    t_c_train = t_c_train,
    t_c_val = t_c_val)

print()
print(linear_model.weight)
print(linear_model.bias)

Epoch 1, Training loss 46.7542, Validation loss 387.6757
Epoch 1000, Training loss 3.6547, Validation loss 32.0106
Epoch 2000, Training loss 2.5501, Validation loss 16.5112
Epoch 3000, Training loss 2.4670, Validation loss 13.1636
Epoch 4000, Training loss 2.4608, Validation loss 12.3133
Epoch 5000, Training loss 2.4603, Validation loss 12.0853
Epoch 6000, Training loss 2.4603, Validation loss 12.0231
Epoch 7000, Training loss 2.4603, Validation loss 12.0060
Epoch 8000, Training loss 2.4602, Validation loss 12.0013
Epoch 9000, Training loss 2.4603, Validation loss 12.0009
Epoch 10000, Training loss 2.4603, Validation loss 12.0009
Epoch 11000, Training loss 2.4603, Validation loss 12.0009
Epoch 12000, Training loss 2.4603, Validation loss 12.0009
Epoch 13000, Training loss 2.4603, Validation loss 12.0009
Epoch 14000, Training loss 2.4603, Validation loss 12.0009
Epoch 15000, Training loss 2.4603, Validation loss 12.0009
Epoch 16000, Training loss 2.4603, Validation loss 12.0009
Epoch 17

In [14]:
x = torch.ones(10, 1)
x

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [15]:
linear_model(x)

tensor([[-10.1314],
        [-10.1314],
        [-10.1314],
        [-10.1314],
        [-10.1314],
        [-10.1314],
        [-10.1314],
        [-10.1314],
        [-10.1314],
        [-10.1314]], grad_fn=<AddmmBackward0>)

In [16]:
t_c = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
t_u = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]
t_c = torch.tensor(t_c).unsqueeze(1) # <1>
t_u = torch.tensor(t_u).unsqueeze(1) # <1>

In [17]:
linear_model = nn.Linear(1, 1)
optimizer = optim.SGD(
    linear_model.parameters(),
    lr=1e-2
)

In [19]:
list(linear_model.parameters())

[Parameter containing:
 tensor([[0.2947]], requires_grad=True),
 Parameter containing:
 tensor([-0.0561], requires_grad=True)]

In [22]:
seq_model = nn.Sequential(
    nn.Linear(1, 13),
    nn.Tanh(),
    nn.Linear(13, 1)
)
seq_model

Sequential(
  (0): Linear(in_features=1, out_features=13, bias=True)
  (1): Tanh()
  (2): Linear(in_features=13, out_features=1, bias=True)
)

In [29]:
[param.shape for param in seq_model.parameters()]

[torch.Size([13, 1]), torch.Size([13]), torch.Size([1, 13]), torch.Size([1])]

In [31]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

0.weight torch.Size([13, 1])
0.bias torch.Size([13])
2.weight torch.Size([1, 13])
2.bias torch.Size([1])


In [37]:
seq_model = nn.Sequential(OrderedDict(
    [
    ('hidden_layer', nn.Linear(1, 13)),
    ('hidden_activation', nn.Tanh()),
    ('output_layer', nn.Linear(13, 1))
]
))
seq_model

Sequential(
  (hidden_layer): Linear(in_features=1, out_features=13, bias=True)
  (hidden_activation): Tanh()
  (output_layer): Linear(in_features=13, out_features=1, bias=True)
)

In [38]:
for name, param in seq_model.named_parameters():
    print(name, param.shape)

hidden_layer.weight torch.Size([13, 1])
hidden_layer.bias torch.Size([13])
output_layer.weight torch.Size([1, 13])
output_layer.bias torch.Size([1])


In [39]:
seq_model.output_layer.bias

Parameter containing:
tensor([-0.2768], requires_grad=True)

In [42]:
training_loop(
    n_epochs=10000,
    optimizer=optimizer,
    model=seq_model,
    loss_fn=nn.MSELoss(),
    t_u_train=t_un_train,
    t_u_val=t_u_val,
    t_c_train=t_c_train,
    t_c_val=t_c_val
)

Epoch 1, Training loss 97.3336, Validation loss 622.4902
Epoch 1000, Training loss 97.3336, Validation loss 622.4902
Epoch 2000, Training loss 97.3336, Validation loss 622.4902
Epoch 3000, Training loss 97.3336, Validation loss 622.4902
Epoch 4000, Training loss 97.3336, Validation loss 622.4902
Epoch 5000, Training loss 97.3336, Validation loss 622.4902
Epoch 6000, Training loss 97.3336, Validation loss 622.4902
Epoch 7000, Training loss 97.3336, Validation loss 622.4902
Epoch 8000, Training loss 97.3336, Validation loss 622.4902
Epoch 9000, Training loss 97.3336, Validation loss 622.4902
Epoch 10000, Training loss 97.3336, Validation loss 622.4902


In [43]:
import matplotlib.pyplot as plt