In [ ]:
import torch
import numpy as np

# Criando um tensor

In [ ]:
tensor_A = torch.rand(3, 3)
tensor_A

tensor([[0.6324, 0.3184, 0.0189],
        [0.7994, 0.2585, 0.7924],
        [0.5002, 0.6341, 0.6143]])

In [ ]:
tensor_B = torch.from_numpy(np.random.rand(3, 3))
tensor_B

tensor([[0.2299, 0.5370, 0.7215],
        [0.7904, 0.0972, 0.4803],
        [0.2208, 0.8440, 0.1320]], dtype=torch.float64)

# Camada convolucional 2D

In [ ]:
input_shape = (8, 3, 16, 16)
x = torch.rand(input_shape)
out_conv = torch.nn.Conv2d(3, 16, 3, padding="same")
out_conv(x).shape

torch.Size([8, 16, 16, 16])

In [ ]:
out_conv = torch.nn.Conv2d(3, 16, 3)
print(out_conv(x).shape)

out_conv = torch.nn.Conv2d(3, 12, (3, 5))
print(out_conv(x).shape)

out_conv = torch.nn.Conv2d(3, 24, (3, 3), stride=(2, 2))
print(out_conv(x).shape)

torch.Size([8, 16, 14, 14])
torch.Size([8, 12, 14, 12])
torch.Size([8, 24, 7, 7])


In [ ]:
#Teste mudando o valor do tamanho dos filtros, dos strides e da imagem.

input_shape = (8, 3, 16, 16)
x = torch.rand(input_shape)

in_channel = 3
out_channel = 24
filter_size = (5,5)
stri = (3,3)


out_conv = torch.nn.Conv2d(in_channel, out_channel, filter_size, stride=stri)
print(out_conv(x).shape)

torch.Size([8, 24, 4, 4])



**Se quiser ir mais a fundo:**

[Documentação ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D)



# Camada convolucional 3D


In [ ]:
input_shape =(8, 3, 16, 16, 16)

x = torch.rand(input_shape)
out_conv = torch.nn.Conv3d(3, 5, 5)
out_conv(x).shape

torch.Size([8, 5, 12, 12, 12])

**Se quiser ir mais a fundo:**

[Documentação ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv3D)


# Pooling

In [ ]:
input_shape =(8, 3, 16, 16)
x = torch.rand(input_shape)

max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2,2))(x)
max_pool_2d.shape

TensorShape([8, 8, 8, 3])

In [ ]:
#Visualize como o pooling 2D faz a redução de dimensionalidade

input_shape = (1, 1, 3, 3)
x = torch.rand(input_shape)
print(x)

max_pool_2d = torch.nn.MaxPool2d(2, stride=1)
print(max_pool_2d(x))

tensor([[[[0.6915, 0.7724, 0.5290],
          [0.5301, 0.6904, 0.3067],
          [0.4211, 0.8669, 0.7050]]]])
tensor([[[[0.7724, 0.7724],
          [0.8669, 0.8669]]]])


**Se quiser ir mais a fundo:**

[Documentação ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPooling2D)

# UpSampling

In [ ]:
input_shape = (8, 3, 16, 16)
x = torch.rand(input_shape)
up_sampl = torch.nn.Upsample((32, 32))
up_sampl(x).shape

torch.Size([8, 3, 32, 32])

In [ ]:
input_shape = (1, 1, 3, 3)
x = torch.rand(input_shape)
print(x)

up_sampl = torch.nn.Upsample((5, 5))
print(up_sampl(x))

tensor([[[[0.7717, 0.5225, 0.9381],
          [0.0808, 0.9149, 0.7152],
          [0.1129, 0.6630, 0.4165]]]])
tensor([[[[0.7717, 0.7717, 0.5225, 0.5225, 0.9381],
          [0.7717, 0.7717, 0.5225, 0.5225, 0.9381],
          [0.0808, 0.0808, 0.9149, 0.9149, 0.7152],
          [0.0808, 0.0808, 0.9149, 0.9149, 0.7152],
          [0.1129, 0.1129, 0.6630, 0.6630, 0.4165]]]])


**Se quiser ir mais a fundo:**

[Documentação ](https://www.tensorflow.org/api_docs/python/tf/keras/layers/UpSampling2D)

# ConvTranspose2D

In [ ]:
input_shape = (8, 3, 16, 16)
x = torch.rand(input_shape)
out_conv = torch.nn.Conv2d(3, 16, 3)
out_conv(x).shape

torch.Size([8, 16, 14, 14])

In [ ]:
input_shape = (8, 3, 16, 16)
x = torch.rand(input_shape)
out_conv = torch.nn.ConvTranspose2d(3, 16, 3)
out_conv(x).shape

torch.Size([8, 16, 18, 18])

# Flatten

In [ ]:
input_shape = (1, 1, 3, 3)
x = torch.rand(input_shape)
print(x)

flat = torch.flatten(x)
flat.shape

tensor([[[[0.5737, 0.9776, 0.8984],
          [0.2312, 0.0915, 0.5160],
          [0.6596, 0.4769, 0.4375]]]])


torch.Size([9])

# Exercício

Dado um input do tamanho (8, 30, 16, 16), crie uma arquitetura estilo autoencoder que retorne um output igual.

Na arquitetura deve ter pelo menos 8 camadas (pelo menos 1 convolucional, 1 upsampling e 1 maxpooling, etc)

In [ ]:
input_shape = (8, 3, 16, 16)

In [ ]:
class UNet(torch.nn.Module):
    def __init__(self, n_class):
        super().__init__()

        #Encoder
        self.e11 = torch.nn.Conv2d(3, 64, kernel_size=3, padding=1)
        self.e12 =  torch.nn.Conv2d(64, 64, kernel_size=3, padding=1)
        self.pool1 =  torch.nn.MaxPool2d(kernel_size=2, stride=2)

        # Decoder
        self.upconv1 =  torch.nn.ConvTranspose2d(1024, 512, kernel_size=2, stride=2)

        # Output layer
        self.outconv = torch.Conv2d(64, n_class, kernel_size=1)

In [ ]:
  def forward(self, x):
        # Encoder
        xe11 = relu(self.e11(x))
        xe12 = relu(self.e12(xe11))

        # Output layer
        out = self.outconv(xe12)

        return out